package software.frisby.web.client;

import software.frisby.web.serial.JsonSerializer;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.SequenceInputStream;
import java.net.URLConnection;
import java.net.http.HttpRequest;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.UUID;

/**
 * Builds the {@link HttpRequest.BodyPublisher} and {@code Content-Type} header value
 * for {@code multipart/form-data} requests.
 * <p>
 * Parts are assembled as a sequence of streams so the file data is never fully
 * buffered into memory.  Chunked transfer encoding is used (no {@code Content-Length}).
 */
final class MultipartBodyBuilder {
    private static final String CRLF = "\r\n";
    private static final String DASHES = "--";
    private static final String DEFAULT_CONTENT_TYPE = "application/octet-stream";
    private static final String CONTENT_DISPOSITION_FORM_DATA_NAME = "Content-Disposition: form-data; name=\"";

    private MultipartBodyBuilder() {
    }

    /**
     * Generates a unique multipart boundary string.
     *
     * @return A boundary string suitable for use in a {@code Content-Type} header.
     */
    static String generateBoundary() {
        return UUID.randomUUID().toString();
    }

    /**
     * Returns the {@code Content-Type} header value for a multipart request with the
     * given boundary.
     *
     * @param boundary The boundary string generated by {@link #generateBoundary()}.
     * @return The full {@code Content-Type} value, e.g.
     * {@code multipart/form-data; boundary=abc123}.
     */
    static String contentType(String boundary) {
        return "multipart/form-data; boundary=" + boundary;
    }

    /**
     * Builds a streaming {@link HttpRequest.BodyPublisher} for the given parts.
     * <p>
     * Parts are assembled in the order provided.  The caller controls the ordering
     * via {@link FormData#parts()}.
     *
     * @param parts      The ordered list of form parts to include.
     * @param boundary   The boundary string for this multipart body.
     * @param serializer The JSON serializer used to serialize {@link FormPart.JsonPart} bodies.
     * @return A body publisher that streams the assembled multipart body.
     */
    static HttpRequest.BodyPublisher build(List<FormPart> parts,
                                           String boundary,
                                           JsonSerializer serializer) {
        return HttpRequest.BodyPublishers.ofInputStream(() -> assembleStream(parts, boundary, serializer));
    }

    private static InputStream assembleStream(List<FormPart> parts,
                                              String boundary,
                                              JsonSerializer serializer) {
        InputStream result = InputStream.nullInputStream();

        boolean first = true;

        for (FormPart part : parts) {
            String partHeader = buildPartHeader(part, boundary, first);
            byte[] headerBytes = partHeader.getBytes(StandardCharsets.UTF_8);
            InputStream headerStream = new ByteArrayInputStream(headerBytes);
            InputStream bodyStream = bodyStreamOf(part, serializer);

            result = new SequenceInputStream(
                    new SequenceInputStream(result, headerStream),
                    bodyStream
            );

            first = false;
        }

        byte[] closingBytes = (CRLF + DASHES + boundary + DASHES + CRLF)
                .getBytes(StandardCharsets.UTF_8);

        return new SequenceInputStream(result, new ByteArrayInputStream(closingBytes));
    }

    private static String buildPartHeader(FormPart part,
                                          String boundary,
                                          boolean first) {
        StringBuilder sb = new StringBuilder();

        if (!first) {
            sb.append(CRLF);
        }

        sb.append(DASHES).append(boundary).append(CRLF);

        if (part instanceof FormPart.FilePart filePart) {
            String contentType = filePart.contentType()
                    .map(MediaType::value)
                    .orElseGet(() -> guessContentType(filePart.fileName()));

            sb.append("Content-Type: ").append(contentType).append(CRLF);
            sb.append(CONTENT_DISPOSITION_FORM_DATA_NAME)
                    .append(filePart.name())
                    .append("\"; filename=\"")
                    .append(filePart.fileName())
                    .append("\"").append(CRLF);
        } else if (part instanceof FormPart.JsonPart jsonPart) {
            sb.append("Content-Type: application/json").append(CRLF);
            sb.append(CONTENT_DISPOSITION_FORM_DATA_NAME)
                    .append(jsonPart.name())
                    .append("\"").append(CRLF);
        } else {
            FormPart.ContentPart contentPart = (FormPart.ContentPart) part;
            sb.append("Content-Type: ").append(contentPart.mediaType().value()).append(CRLF);
            sb.append(CONTENT_DISPOSITION_FORM_DATA_NAME)
                    .append(contentPart.name())
                    .append("\"").append(CRLF);
        }

        sb.append(CRLF);
        return sb.toString();
    }

    private static InputStream bodyStreamOf(FormPart part, JsonSerializer serializer) {
        if (part instanceof FormPart.FilePart filePart) {
            return filePart.stream();
        }

        if (part instanceof FormPart.JsonPart jsonPart) {
            return new ByteArrayInputStream(RequestBodyEncoder.serializeBody(jsonPart.body(), serializer));
        }

        FormPart.ContentPart contentPart = (FormPart.ContentPart) part;
        return new ByteArrayInputStream(
                contentPart.content().getBytes(StandardCharsets.UTF_8)
        );
    }


    private static String guessContentType(String fileName) {
        String contentType = URLConnection.guessContentTypeFromName(fileName);

        return null != contentType ? contentType : DEFAULT_CONTENT_TYPE;
    }
}

